services:
  # Development service with hot-reloading
  docusaurus-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./site:/app
    environment:
      - NODE_ENV=development

  # Production service
  docusaurus-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: serve
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
